### ISSUE TITLE
redis-server binary not installed from requirements

### ISSUE THREAD

**Issue by machawk1** [atomotic/isbn-authors#2]
I am playing naive and following the installation instructions in the README verbatim.

After installing the Python requirements via `pip`, I attempt to start invoke the redis-server as directed but am told, `redis-server: command not found`.

You may want to provide guidance to users on how to obtain the needed binary. Even a link to external instructions would suffice. For macOS, `brew install redis` fetches and installs what's needed.

macOS 10.12.2, Python 2.7.11

**Comment by atomotic** [comment]
yeah sorry, i improved a bit the README.
everything is very raw, and focused to have it running on heroku

other fixes will follow, thanks.
